### ISSUE TITLE
Gallery HTML build broken after upgrade vom 0.11.1 to 0.12.0

### ISSUE THREAD

**Issue by tamasgal** [sphinx-gallery/sphinx-gallery#1093]
My nightly doc-builds of multiple projects suddenly failed without any change to the software projects themself and I tracked it down to a single change between the last successful build and the current failing builds: the upgrade of `sphinx-gallery` from v0.11.1 to 0.12.0.

I am currently running these versions under Python 3.10.9:
```
$ pip freeze | grep -i sphinx
Sphinx==6.1.3
sphinx-autoapi==2.0.1
sphinx-gallery==0.12.0
sphinx-rtd-theme==0.5.1
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib-versioning==2.2.1
sphinxcontrib.applehelp==1.0.3
```

The initial error log in the CI was:

```
[AutoAPI] Reading files... [ 95%] /builds/km3py/km3io/src/km3io/_definitions/applications.py
[AutoAPI] Reading files... [100%] /builds/km3py/km3io/src/km3io/utils/kprinttree.py
[AutoAPI] Mapping Data... [  4%] /builds/km3py/km3io/src/km3io/rootio.py
Extension error (sphinx_gallery.gen_gallery):
Handler <function write_api_entries at 0x7f4e63070940> for event 'autodoc-process-docstring' threw an exception (exception: 'show_api_usage')
make: *** [Makefile:20: html] Error 2

Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

and after reproducing it locally, I ran the command with more verbosity and got this:

```python
[app] emitting event: 'autodoc-process-docstring'('method', '__init__', None, None, ['Initialize self.  See help(type(self)) for accurate signature.'

Traceback (most recent call last):
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/sphinx_gallery/gen_gallery.py", line 743, in write_api_entries
    if app.config.sphinx_gallery_conf['show_api_usage'] is False:
KeyError: 'show_api_usage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 279, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/sphinx/application.py", line 262, in __init__
    self._init_builder()
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/sphinx/application.py", line 335, in _init_builder
    self.events.emit('builder-inited')
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/autoapi/extension.py", line 156, in run_autoapi
    sphinx_mapper_obj.map(options=app.config.autoapi_options)
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/autoapi/mappers/python/mapper.py", line 343, in map
    super().map(options)
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/autoapi/mappers/base.py", line 297, in map
    for obj in self.create_class(data, options=options):
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/autoapi/mappers/python/mapper.py", line 382, in create_class
    for child_obj in self.create_class(
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/autoapi/mappers/python/mapper.py", line 382, in create_class
    for child_obj in self.create_class(
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/autoapi/mappers/python/mapper.py", line 395, in create_class
    self.app.emit(
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/sphinx/application.py", line 458, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function write_api_entries at 0x11001fac0> for event 'autodoc-process-docstring' threw an exception (exception: 'show_api_usage')

Extension error (sphinx_gallery.gen_gallery):
Handler <function write_api_entries at 0x11001fac0> for event 'autodoc-process-docstring' threw an exception (exception: 'show_api_usage')
```

So apparently it chokes on a missing entry in the `sphinx_gallery_conf` named `'show_api_usage'`.

```
    if app.config.sphinx_gallery_conf['show_api_usage'] is False:
KeyError: 'show_api_usage'
```

I added that in my `conf.py`:

```python
sphinx_gallery_conf = {
    "backreferences_dir": "modules/generated",
    "default_thumb_file": "_static/default_gallery_thumbnail.png",
    "examples_dirs": "../examples",  # path to your example scripts
    "gallery_dirs": "auto_examples",  # path to where to save gallery generated output
    "show_memory": True,
    "show_api_usage": True,
}
```

but then got this:

```
[AutoAPI] Rendering Data... [ 95%] km3io._definitions.trigger
[AutoAPI] Rendering Data... [100%] km3io._definitions.daqdatatypes

generating gallery...

Configuration error:
Unknown key(s) in sphinx_gallery_conf:
'api_entries'
make: *** [html] Error 2
```

changing it to `False` threw another `Extension error`:

```
[AutoAPI] Rendering Data... [ 95%] km3io._definitions.trigger
[AutoAPI] Rendering Data... [100%] km3io._definitions.daqdatatypes

generating gallery...

Extension error (sphinx_gallery.gen_gallery):
Handler <function generate_gallery_rst at 0x104143400> for event 'builder-inited' threw an exception (exception: process no longer exists (pid=77972))
make: *** [html] Error 2
```

So I cranked up the verbosity again with `sphinx-build -M html "." "_build" -vvv` and found another problem related to `psutil` (installed version is `psutil==5.9.4`, but it works with `sphinx-gallery==0.11.1`):

```
Traceback (most recent call last):
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/psutil/_common.py", line 443, in wrapper
    ret = self._cache[fun]
AttributeError: 'Process' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/psutil/_common.py", line 443, in wrapper
    ret = self._cache[fun]
AttributeError: 'Process' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/psutil/_common.py", line 446, in wrapper
    return fun(self)
  File "/Users/tamasgal/Dev/km3io/venv/lib/python3.10/site-packages/psutil/_psosx.py", line 381, in _get_pidtaskinfo
    ret = cext.proc_pidtaskinfo_oneshot(self.pid)
ProcessLookupError: [Errno 3] No such process (originated from proc_pidinfo())
```

Any ideas?
